apiVersion: batch.init.sre.ryu-tech.blog/v1alpha1
kind: InitJob
metadata:
  name: migrate-db
spec:
  jobTemplate:
    metadata:
      labels:
        app: migrate-db
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: migration
              image: alpine
              command: ["sh", "-c", "echo 'Running DB migration...' && echo 'CREATE TABLE IF NOT EXISTS users (id INT PRIMARY KEY);' && echo 'Migration complete'"]
