name: Tests

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    permissions:
      contents: read
    uses: S-mishina/reusable-workflows/.github/workflows/go-test.yml@main
    with:
      test-command: "make test"
